% =========================================================
% Script: validateReproducibility.m
% Purpose: Verify that the restructured codebase produces RMSE
%          and failure-rate values consistent with the benchmark
%          CSV files generated by the original submission code.
% Paper  : Sensors-100615-2025
% Run    : From the repository root after running setup_path.m
% =========================================================
%
% WHAT THIS SCRIPT CHECKS
%   Runs exactly the same pipeline as paperCodeS1.m, restricted to:
%     - Kf = 2  (default beam budget, Table I)
%     - ASNR in {0, 15} dB (threshold and high-SNR conditions)
%   for both methods (Cov-guided and Sectorization).
%   Compares RMSE_rad and FailRate against data/S1_aggregates.csv.
%
%   The parfor body below is copied verbatim from paperCodeS1.m
%   for kf=2 — no reimplementation. This is the safest possible
%   test: it runs exactly the code that generated the benchmark CSV.
%
% TOLERANCE POLICY
%   RMSE     : relative tolerance 3%   (Monte Carlo variance at 1e4 trials)
%   FailRate : absolute tolerance 0.5 percentage points
%
%   Timing columns (t_*_ms in A1_timing_table.csv) are NOT checked.
%   Wall-clock times are hardware-dependent; the benchmark CSV was
%   generated on an older desktop and will differ on the current machine.
%
% EXPECTED RUNTIME
%   ~5-10 min with parfor (6-8 workers recommended).
% =========================================================

clearvars;
fprintf('\n=== CovGuided-ESPRIT Reproducibility Validation ===\n');
fprintf('Paper: Sensors-100615-2025\n');
fprintf('Date : %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM'));

%% ---- 0. Path check -----------------------------------------------------
required_fns = {'centered_contiguous_mask', 'tls_esprit', ...
                'estimate_powers_course', 'estimate_powers_fine', ...
                'sectorize_dft_beams', 'select_beamsets_from_sectorized_cov', ...
                'unitary_esprit_sparse', 'toeplitz_projection', 'getSimParams'};
missing = {};
for i = 1:numel(required_fns)
    if exist(required_fns{i}, 'file') ~= 2
        missing{end+1} = required_fns{i}; %#ok<AGROW>
    end
end
if ~isempty(missing)
    error('Missing functions on path:\n  %s\nRun setup_path.m first.', ...
          strjoin(missing, '\n  '));
end
fprintf('[OK] All required functions found on path.\n');

%% ---- 1. Load benchmark CSV ---------------------------------------------
csv_path = fullfile(fileparts(mfilename('fullpath')), '..', 'data', 'S1_aggregates.csv');
if ~isfile(csv_path)
    error('Benchmark file not found:\n  %s', csv_path);
end
T_bench = readtable(csv_path);
fprintf('[OK] Loaded benchmark: %s (%d rows)\n\n', csv_path, height(T_bench));

%% ---- 2. Parameters — identical to paperCodeS1.m -----------------------
% Hardcoded to match the original submission script exactly.
% getSimParams is verified on path above but not called here,
% so any future change to getSimParams cannot affect this test.

M   = 32;
N   = 100;
NRF = 12;
d   = 3;

pows     = [0.95, 0.5, 0.1];
R_source = diag(pows);
Psqrt    = diag(sqrt(pows/2));
mu_true  = [-2.1; 0.5; 2.5];

Atrue   = exp(1i * (0:M-1).' * mu_true.');
phase_k = exp(1i*(M-1)*pi*(0:M-1).'/M);

maskIdx  = centered_contiguous_mask(M, NRF);
mIdxFlip = NRF:-1:1;

R_signal = Atrue * R_source * Atrue';

kf   = 2;    % fixed beam budget for this validation
kThr = 3;

% ASNR points (subset of S1's [0 5 10 15])
ASNR_val = [0, 15];
noiseVar = real(trace(R_signal)) ./ (M * 10.^(ASNR_val / 10));

% Selector options — identical to paperCodeS1.m (prune_topq = 0)
opts_sel = struct('eig_tol_scale', 1e-6, 'tikhonov_gamma', 0, ...
                  'alpha', 0.5, 'normalize_score', true, 'prune_topq', 0);

totalIter = 1e4;

% CRB at validation ASNR points (same formula as paperCodeS1.m)
PorthA = eye(M) - Atrue * pinv(Atrue);
derA   = (1i * transpose(0:M-1)) .* Atrue;
H      = transpose(derA' * PorthA * derA);
sqrtCRB_val = zeros(1, numel(ASNR_val));
for ni = 1:numel(ASNR_val)
    nv = noiseVar(ni);
    secondTerm = ((Atrue' * Atrue) * R_source) / nv;
    firstTerm  = eye(d) + secondTerm;
    CRBinvterm = diag(inv(real((R_source * (firstTerm \ secondTerm)) .* H)));
    sqrtCRB_val(ni) = sqrt(sum((nv / (2*N)) * CRBinvterm) / d);
end

fprintf('Validating: Kf=%d, ASNR = [%s] dB, %d trials each.\n', ...
        kf, num2str(ASNR_val, '%+d '), totalIter);
fprintf('Pipeline: parfor body copied verbatim from paperCodeS1.m.\n\n');

%% ---- 3. Monte Carlo — exact copy of paperCodeS1 parfor body for kf=2 --
numASNR       = numel(ASNR_val);
RMSE_fine_out = zeros(1, numASNR);
RMSE_wide_out = zeros(1, numASNR);
fail_fine_out = zeros(1, numASNR);
fail_wide_out = zeros(1, numASNR);

for sIdx = 1:numASNR

    nvStd = sqrt(noiseVar(sIdx) / 2);
    thr   = kThr * max(sqrtCRB_val(sIdx), 1e-12);

    e_trials_fine = nan(totalIter, 1);
    e_trials_wide = nan(totalIter, 1);

    nIter   = totalIter;
    asnrNow = ASNR_val(sIdx);
    q = parallel.pool.DataQueue;
    afterEach(q, @(~) updateProgress(1, nIter, asnrNow));
    updateProgress(NaN, nIter, asnrNow);

    % -------------------------------------------------------------------
    % The parfor body below is the exact code from paperCodeS1.m,
    % with the inner kk-loop collapsed to kf=2 only.
    % Variable names are preserved. Nothing is reimplemented.
    % -------------------------------------------------------------------
    parfor iter = 1:totalIter

        s = RandStream('Threefry', 'Seed', 5489);
        s.Substream = iter;
        RandStream.setGlobalStream(s);

        %% Coarse stage [paperCodeS1.m lines 97–121]
        S = Psqrt * (randn(d, N) + 1i*randn(d, N));
        X = Atrue * S;

        Z        = nvStd * (randn(M, N) + 1i*randn(M, N));
        Y_coarse = X + Z;

        Yb_coarse = Y_coarse(maskIdx, :);    % NRF x N — centered mask
        Yb_wideES = Y_coarse(1:NRF, :);     % NRF x N — first NRF rows (baseline)

        RY_coarse = (Yb_coarse * Yb_coarse') / N;
        RY_coarse = (RY_coarse + RY_coarse') / 2;
        RY_wideES = (Yb_wideES * Yb_wideES') / N;
        RY_wideES = (RY_wideES + RY_wideES') / 2;

        RY_fba = (RY_coarse + conj(RY_coarse(mIdxFlip, mIdxFlip))) * 0.5;

        mu_coarse = tls_esprit(RY_fba,    d);
        mu_wide   = tls_esprit(RY_wideES, d);

        [~, ~, mu_courseSort, R_course] = estimate_powers_course(RY_fba,    maskIdx, mu_coarse, M);
        [~, ~, mu_wideSort,   ~       ] = estimate_powers_course(RY_wideES, 1:NRF,   mu_wide,   M); %#ok<PFBNS>

        %% Fine stage snapshot [paperCodeS1.m lines 123–130]
        Z2     = nvStd * (randn(M, N) + 1i*randn(M, N));
        S2     = Psqrt * (randn(d, N) + 1i*randn(d, N));
        X2     = Atrue * S2;
        Y_fine = X2 + Z2;

        Yb_full = phase_k .* fft(Y_fine, M, 1);

        %% Beam selection [paperCodeS1.m lines 143–149]
        % Cov-guided: window = 2*kf, select kf beams via covariance score
        beamGroups_fine = sectorize_dft_beams(mu_courseSort, M, 2*kf, 1);
        selBeams_fine   = select_beamsets_from_sectorized_cov(R_course, beamGroups_fine, kf, opts_sel);
        SoICols_fine    = unique(cell2mat(selBeams_fine)).';

        % Sectorization baseline: window = kf, take ALL beams in group directly
        beamGroups_wide = sectorize_dft_beams(mu_wideSort, M, kf, 1);
        SoICols_wide    = unique(cell2mat(beamGroups_wide)).';

        %% Fine ESPRIT [paperCodeS1.m lines 152–173]
        Yb_fine = Yb_full(SoICols_fine, :);
        Yb_wide = Yb_full(SoICols_wide, :);

        mu_fine      = unitary_esprit_sparse(Yb_fine, SoICols_fine, d, M);
        mu_wide_fine = unitary_esprit_sparse(Yb_wide, SoICols_wide, d, M);

        RY_fine = (Yb_fine * Yb_fine') / N;
        RY_fine = (RY_fine + RY_fine') / 2;
        RY_wide = (Yb_wide * Yb_wide') / N;
        RY_wide = (RY_wide + RY_wide') / 2;

        [~, ~, mu_fineSort,      ~] = estimate_powers_fine(RY_fine, SoICols_fine, mu_fine,      M);
        [~, ~, mu_wideSort_fine, ~] = estimate_powers_fine(RY_wide, SoICols_wide, mu_wide_fine, M);

        e_trials_fine(iter) = sqrt(mean(angle(exp(1i*(mu_true - mu_fineSort))).^2));
        e_trials_wide(iter) = sqrt(mean(angle(exp(1i*(mu_true - mu_wideSort_fine))).^2));

        send(q, 1);

    end % parfor

    RMSE_fine_out(sIdx) = sqrt(mean(e_trials_fine.^2));
    RMSE_wide_out(sIdx) = sqrt(mean(e_trials_wide.^2));
    fail_fine_out(sIdx) = mean(e_trials_fine > thr) * 100;  % percent
    fail_wide_out(sIdx) = mean(e_trials_wide > thr) * 100;

end % ASNR loop

%% ---- 4. Compare against benchmark CSV ----------------------------------
% S1_aggregates.csv: FailRate column is a fraction (0..1), not percent.
% We multiply by 100 before comparing with our percentage values.

tol_rmse_rel = 0.03;  % 3% relative
tol_fail_abs = 0.5;   % 0.5 percentage-point absolute

RMSE_new    = [RMSE_fine_out; RMSE_wide_out];
FailNew_pct = [fail_fine_out; fail_wide_out];
method_labels = {'Cov-guided', 'Sectorization'};

fprintf('\n%-14s  %-6s  %-12s  %-12s  %-10s  %-13s  %s\n', ...
        'Method', 'ASNR', 'RMSE_new', 'RMSE_csv', 'Err_rel%', ...
        'Fail_new|csv%', 'Status');
fprintf('%s\n', repmat('-', 1, 84));

all_pass = true;

for mi = 1:2
    mname = method_labels{mi};
    for ai = 1:numASNR
        asnr = ASNR_val(ai);

        row = T_bench( ...
            T_bench.Kf == kf & ...
            T_bench.ASNR_dB == asnr & ...
            strcmp(T_bench.method, mname), :);

        if isempty(row)
            fprintf('%-14s  %+3d dB  [no matching row in CSV — skipping]\n', mname, asnr);
            continue
        end

        rmse_csv  = row.RMSE_rad;
        fail_csv  = row.FailRate * 100;  % fraction -> percent
        rmse_new  = RMSE_new(mi, ai);
        fail_new  = FailNew_pct(mi, ai);

        err_rel   = abs(rmse_new - rmse_csv) / rmse_csv * 100;
        fail_diff = abs(fail_new - fail_csv);

        pass   = (err_rel < tol_rmse_rel * 100) && (fail_diff < tol_fail_abs);
        status = pick(pass, 'PASS', '*** FAIL ***');
        if ~pass, all_pass = false; end

        fprintf('%-14s  %+3d dB  %-12.4f  %-12.4f  %-10.2f  %+5.1f | %-5.1f    %s\n', ...
                mname, asnr, rmse_new, rmse_csv, err_rel, fail_new, fail_csv, status);
    end
end

fprintf('%s\n', repmat('-', 1, 84));

if all_pass
    fprintf('\n[RESULT] ALL CHECKS PASSED.\n');
    fprintf('         Restructured codebase is numerically consistent with benchmark CSVs.\n');
    fprintf('         Safe to commit and push to GitHub.\n');
else
    fprintf('\n[RESULT] ONE OR MORE CHECKS FAILED. Do not commit until resolved.\n');
    error('Reproducibility validation failed. See table above.');
end

fprintf(['\nNOTE: Timing columns in A1_timing_table.csv are NOT validated here.\n' ...
         '      Wall-clock benchmarks are hardware-dependent. The benchmark CSV\n' ...
         '      was generated on an older desktop; the current machine (upgraded\n' ...
         '      CPU/motherboard/RAM) will produce faster timings. Only RMSE and\n' ...
         '      FailRate columns are machine-independent benchmarks.\n\n']);

%% ---- Local helpers -------------------------------------------------------

function updateProgress(incr, nIter, asnrVal)
persistent count lastPct
if isnan(incr)
    count = 0; lastPct = 0;
    fprintf('\rASNR = %+3.0f dB  [%s]   0%%', asnrVal, repmat(' ', 1, 40));
    return
end
if isempty(count), count = 0; lastPct = 0; end
count = count + 1;
pct   = floor(100 * count / nIter);
if pct >= lastPct + 5 || count == nIter
    lastPct = pct;
    nBars   = round(pct / 100 * 40);
    fprintf('\rASNR = %+3.0f dB  [%s%s] %3d%%', asnrVal, ...
            repmat('=', 1, nBars), repmat(' ', 1, 40 - nBars), pct);
    if count == nIter, fprintf('\n'); end
end
end

function out = pick(cond, a, b)
if cond, out = a; else, out = b; end
end
